### ISSUE TITLE
WebSQL vs. IndexDB

### ISSUE THREAD

**Issue by mike-seekwell** [superhuman/fts#1]
@ConradIrwin Did you guys stick with WebSQL or move everything over to IndexDB? We have some similar needs but in a completely different space. WebSQL fits much better, but we're obviously concerned with the deprecation.

**Comment by ConradIrwin** [comment]
@mike-seekwell we stuck with WebSQL — it's significantly faster, and much easier to work with, see https://groups.google.com/a/chromium.org/forum/#!topic/storage-dev/0njGY5N6wRs.

I talked with the Chrome team about it at the time, and they're keen to find a replacement that works to replace it before deprecating it completely; and so I think it's a relatively safe path to head down (the last idea I heard was providing a fast block-storage API to WASM so that we could compile SQLite ourselves; it might be a bit slower than native SQLite, but should still be much faster than IndexedDB, and not require significant code changes).

**Comment by mike-seekwell** [comment]
that's great to hear, thanks for the info @ConradIrwin !

A WASM solution sounds interesting, hope they pursue that.
